import type { CompanySettings } from "@/types";

/** Shipped defaults — used to seed a fresh store and as an offline fallback. */
export const DEFAULT_SETTINGS: CompanySettings = {
  companyName: "Cement Plant Industries",
  reportTitle: "CEMENT STOCK",
  pdfHeader: "Daily Stock Report",
  pdfFooter: "Confidential — Generated by CPSM",
  bagWeightMt: 0.05,
  defaultTheme: "system",
};
